Don't assume that “finished” key always exists.
Fixes:

    Traceback (most recent call last):
      File ".../appfoyer/appfoyer", line 10, in <module>
        cli.main()
      File ".../appfoyer/lib/cli.py", line 85, in main
        return cmd(options, **match.groupdict())
      File ".../appfoyer/lib/cli.py", line 96, in show_history
        if build['finished'] is None:
    KeyError: 'finished'